# .streamlit/secrets.toml
[gcs]
GCS_BUCKET_NAME="Bucket"
GEMINI_API_KEY="key-6RUfGTNv6Ldv0Y6zd_pw"
GOOGLE_CLOUD_PROJECT = 'voting-2024'
[gcp_service_account]
type = 'service_account'
project_id =  "voting-2024"
private_key_id =  "asdffasdf"
private_key =  """-----BEGIN PRIVATE KEY-----
asdfffnananan+oainzKUGuL2JegcPeDQyxsHIkOBnbejsZSZKMVzsDasdfR+JIWru5JZR70bxiFN2TMy3dZKKHl4wyGfYH2mC356hm6CP5yFHGIBn\nItdoc1gI5iDRe6NiihvgoLl2X5MTj6GG1tmo6ln+4hrIM3TcqjmN9C3/BHLHrLWB\n5MFvU+cBpny08aOW2kS0N7fuYuDOFsGN+b9g7m+MAZoWt5odft3aLezKv9d03SDZ\n8N8Ldf6U7GzTILIsqTcMqfbUa3ZM1YTn7I5ypo7LxAYOcjsqYl/tTI+mpVSxidXx\n04QV3GI7AgMBAAECggEAU9WBLBiKNXrdxk7KKEIZ/ePFHpzItH1BLaF8rdZdoGg4\nR3i6v1cungELWM0J6mElgnPRbYXGzoExjZdsy+UY8r6cpRrwguhI//SsReD2bkrs\nHhg4YbZm3GEsB9jJSFz6vQNdBH1ViC6dSlk6Lslm9uwUOdEEn6bl8XPPuzeUnu6N\nNrCWO1a2yOkfFe26wUxrTk7iPs9AIsy4puLFAi9lDxiJfAyLufnW1PjcoMDbZa3m\n6ZkgTTwSRbfrMxc6QnUe8q1FUHGYgGGfL5Ws2AizlHB2PwaMqztAPf8giqOwCwoW\nNxL0VfMI+wFgzRngmzdp85QNibgOq0dtaVy17p5DhQKBgQDrXydvdvdpl/ps3kux\nAOjy0wwM5GQamQAKKx3XAhvCN4VCsUPUtj9QT5elaD8U8QVpfjekHKeN5yqZF6Ge\n1m3vc1jYB+yCrh3v3nHlZzs9I3orsdmfw9aINXn6VMqTaK3k2tNSs+VOGL//bmFA\nZpEFyV0gdzF/SnToBJHlldVw/wKBgQC/F7Hc+g6Xc7SEx+eezGqZIdlJeCr8Mh9D\nMO2QfuPvzapfRyvTqYCXj6rpCNbjZiiG65pSU0RkiIrIAtPfrxZSn/ze+puwWWig\nzWqDkFDYenrIeKHGeG1GSU51sxtHeJ8m+03aHHgqWJgn26UvER0BSzWYObnADMPO\nFm7I9tWSxQKBgAjGHEc4bRKfmrMyOioX+ZcLrPhSDzU6nNjEMLGSH4zG2w3YY8nr\nHUMWJHYDA875CRWcoeBZPRm6E0lvqxOrtJ9nclljOjrI2M7XQPGnPnsR9nzofU9K\nUpXzQF/Hh2GlVk4gph4AHL0jiQyxhaiL6j4H+pO6PbscAG2htfqT8kfrAoGAG8Uh\nv+9G95OFBFbYvicOxro4jYi9FnFiQa12mK0YCt1kiPwazmOvoFbsi3kRYXKTKShM\nAPLA2atOH8rpZ3RWViOR6AWbYoFbxyKS/BOY7BzAgymkuOb/WluE323r5PMOjeev\nZKcGf4Doe8Jbuv9Nq8Z2P20EJXi1a9mut93HI9ECgYBdtLyB7HpSUB4ToByfz4ul\nv47Kic/X5bn1s7KObOOQz3HeI24k61o5k6HV58ZrDtxWDrITd1zdf6eF2C37lF3O\nhONm568aDUryalGrMhJG52CaATbf/aTiFcwFTg4nBwXpiGkBKT2o+PyKahIKMN4+\nnySc7l7nkN0afEoqM7ov2A==
-----END PRIVATE KEY-----"""
client_email =  "gediminas-local@voting-2024.iam.gserviceaccount.com"
client_id =  "random"
auth_uri =  "https://accounts.google.com/o/oauth2/auth"
token_uri =  "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url =  "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url =  "https://www.googleapis.com/robot/v1/metadata/x509/gediminas-local%40voting-2024.iam.gserviceaccount.com"
universe_domain =  "googleapis.com"

